name: Build VuePress Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build VuePress site
        run: npm run docs:build

      - name: Copy build output to /docs
        run: npm run postbuild

      - name: List docs directory (debug)
        run: ls -l docs
